fix: add metadata to code snippet
Error raised without metadata: ```TypeError: make_searchable() missing 1 required positional argument: 'metadata'```